# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 659c1fb42049f5f6bfdf715fe13e0256fced3286d8448f039d11f6a70f1ce30ddb4d1d821772b18bcdf8bff344d7917e3f29c23f3fd2bec52c452e1a9901ac1b

test:
  secret_key_base: 87df850e9f77df3f13c10ebbfba52bcc9c6da6009bb5e9d9d017417ecb55c2810f69607ea03298ac3e3893026be39525fed41a60593a2c442c7ca3dd95b0240b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
